### PR TITLE
Catppuccin Inspired color scheme

### PR DESCRIPTION
**Pull request by psymole**
Added a scheme for Ble.sh
Inspired by the catppuccin mocha color scheme. 

initial idea/work from https://github.com/akinomyoga/ble.sh/discussions/411#discussioncomment-10088978

### CODE REVIEW

**Comment by akinomyoga** [comment]
> initial idea/work from [akinomyoga/ble.sh#411 (reply in thread)](https://github.com/akinomyoga/ble.sh/discussions/411#discussioncomment-10088978)

Thanks! Could you also mention this link and the original author @abhijeeth-babu in the added file?

**Comment by akinomyoga** [comment]
@abhijeeth-babu We want to include a derivative work of your post at https://github.com/akinomyoga/ble.sh/discussions/411#discussioncomment-10088978. Can we include the color settings under the MIT license? If you want to specify a license (that is compatible with the MIT license for the rest of the code), please also tell us that.

**Comment by psymole** [comment]
> > initial idea/work from [akinomyoga/ble.sh#411 (reply in thread)](https://github.com/akinomyoga/ble.sh/discussions/411#discussioncomment-10088978)
> 
> Thanks! Could you also mention this link and the original author @abhijeeth-babu in the added file?
> 
> **edit**: If you like, you may also add your copyright notice in the file, but it's not mandatory because the history will be recorded by Git.

Done!. No need for copyright on my end. 
Thanks!

**Comment by akinomyoga** [comment]
Thanks! I'll wait for @abhijeeth-babu if he has any opinion on this. If there's no reply, I'll merge it with the current version.

**Comment by abhijeeth-babu** [comment]
> Thanks! I'll wait for @abhijeeth-babu if he has any opinion on this. If there's no reply, I'll merge it with the current version.

Hi! Thanks for mentioning me in the patch. I have no issues from my end with regards to the licensing.

**Comment by akinomyoga** [comment]
@abhijeeth-babu Thank you for taking the time to reply!

**Comment by akinomyoga** [comment]
Thanks to both of you! I've merged it.

**Pull request merged**
